name: Website Preview Deploy

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types:
      - automated-pr

jobs:
  publish:
    environment: staging
    runs-on: ubuntu-latest
    env:
      REF: ${{ (github.event.event_type == 'automated-pr' && github.event.client_payload.branch) || github.head_ref || github.ref }}
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF }}
          submodules: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: PNPM install
        run: pnpm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build
        run: ./scripts/build.sh

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ env.REF }}
          environment: staging

      - name: Deploy to Staging
        id: deploy-staging
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=1984vc-production --branch=staging

      - name: Update deployment status (success)
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: ${{ steps.deploy-staging.outputs.deployment-url }}
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
