name: Website Staging Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: NPM install
        run: npm ci

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build
        run: ./scripts/build.sh

      - name: Deploy to Production
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=1984vc-production --branch=main
