name: Website Preview Deploy

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types:
      - automated-pr

jobs:
  publish:
    environment: staging
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: NPM install
        run: npm ci

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build
        run: ./scripts/build.sh

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: staging

      - name: Deploy to Staging
        id: deploy-staging
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=1984vc-production --branch=staging

      - name: Update deployment status (success)
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: ${{ steps.deploy-staging.outputs.deployment-url }}
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
