name: Website Production Deploy

on:
  push:
    branches:
      - main # Trigger only on push to main

jobs:
  publish:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish using shared action
        uses: ./.github/actions/publish-cloudflare
        with:
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_project_name: 1984vc-production # Hardcoded project name for production
          branch_name: main # Hardcoded branch name for production
