name: Pull latest content push and deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # Run at 5 PM ET (21:00 UTC)

permissions:
  contents: write

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Run import script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: bash scripts/import-notion.sh

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push changes
        id: commit # Add an ID to reference this step's output
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git commit -m "Automated build changes"
          git push origin main
          echo "pushed=true" >> $GITHUB_OUTPUT # Output that push happened

      - name: Build
        if: steps.git-check.outputs.changes == 'true'
        run: ./scripts/build.sh

      - name: Deploy to Production
        if: steps.git-check.outputs.changes == 'true'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=1984vc-production --branch=main
